server:
  port: 9000

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    static-path-pattern: /static/**

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: KmMG3XfXHbrHR615L_wJ
            client-secret: 4MPjYJTL6T
            authorization-grant-type: authorization_code
            client-name: modu_prj
            redirect-uri: http://localhost:9000/login/oauth2/code/naver
            scope: email, profile
          google:
            client-id: 120509134525-gsbvf6lanktgk58g8nec8bdqv8519kfc.apps.googleusercontent.com
            client-secret: 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
            authorization-grant-type: authorization_code
            client-name: modu-google
            redirect-uri: http://localhost:9000/login/oauth2/code/google
            scope: email, profile
          kakao:
            client-id: b250e6a0b93302fe83e1aee8f85dbd48
            client-secret: abignxaNxbzgFjdY8Oz6wMRyYYebk1Oi
            authorization-grant-type: authorization_code
            client-name: modu_prj
            redirect-uri: http://localhost:9000/login/oauth2/code/kakao
            scope: profile_nickname, account_email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            issuerUri: https://kauth.kakao.com
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
#            userInfoUri: https://kapi/kakao.com/v1/oidc/userinfo
            jwkSetUri: https://kauth.kakao.com/.well-known/jwks.json
            userNameAttribute: id

