server:
  port: 8083

# local (h2)
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/modu_prj
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        format_sql: true

# local (mysql)



# prod