# local (h2)

server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/modu_prj
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create


logging:
  level:
    org.hibernate.sql: debug

---
# local (mysql)


---
# prod