server:
  port: 8085

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: test
    redis:
      host: localhost
      port: 6379

#logging:
#  level:
#    root: debug

logging:
  level:
    org.springframework.data.mongodb: DEBUG